{
 "errors": {
  "snowflake.connector": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/__init__.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/__init__.py'",
    ""
   ]
  },
  "snowflake.connector.auth": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/auth.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/auth.py'",
    ""
   ]
  },
  "snowflake.connector.auth_default": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/auth_default.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/auth_default.py'",
    ""
   ]
  },
  "snowflake.connector.auth_oauth": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/auth_oauth.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/auth_oauth.py'",
    ""
   ]
  },
  "snowflake.connector.azure_util": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/azure_util.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/azure_util.py'",
    ""
   ]
  },
  "snowflake.connector.chunk_downloader": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/chunk_downloader.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/chunk_downloader.py'",
    ""
   ]
  },
  "snowflake.connector.compat": {
   "exception": "The subprocess /usr/share/miniconda/envs/test/bin/python was killed. Maybe out of memory?",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/cache.py\", line 110, in wrapper",
    "    return dct[key]",
    "KeyError: ((), frozenset())",
    "",
    "During handling of the above exception, another exception occurred:",
    "",
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/cache.py\", line 110, in wrapper",
    "    return dct[key]",
    "KeyError: (('getattr_paths', 'False'), frozenset({('default', None)}))",
    "",
    "During handling of the above exception, another exception occurred:",
    "",
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/subprocess/__init__.py\", line 241, in _send",
    "    pickle_dump(data, self._get_process().stdin, PICKLE_PROTOCOL)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/_compatibility.py\", line 42, in pickle_dump",
    "    file.flush()",
    "BrokenPipeError: [Errno 32] Broken pipe",
    "",
    "During handling of the above exception, another exception occurred:",
    "",
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/helpers.py\", line 488, in wrapper",
    "    return func(self, line, column, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 213, in complete",
    "    return completion.complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/completion.py\", line 169, in complete",
    "    cached_name, completion_names = self._complete_python(leaf)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/completion.py\", line 310, in _complete_python",
    "    completion_names += self._complete_global_scope()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/completion.py\", line 376, in _complete_global_scope",
    "    completion_names += filter.values()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 243, in values",
    "    return [n for filter in self._filters for n in filter.values()]",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 243, in <listcomp>",
    "    return [n for filter in self._filters for n in filter.values()]",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 93, in values",
    "    for name_key in self._used_names",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 88, in _convert_names",
    "    return [self.name_class(self.parent_context, name) for name in names]",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 88, in <listcomp>",
    "    return [self.name_class(self.parent_context, name) for name in names]",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 95, in <genexpr>",
    "    _get_definition_names(self._used_names, name_key),",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 122, in _filter",
    "    return list(self._check_flows(names))",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/filters.py\", line 137, in _check_flows",
    "    origin_scope=self._origin_scope",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/flow_analysis.py\", line 85, in reachability_check",
    "    return _break_check(context, value_scope, first_flow_scope, node)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/flow_analysis.py\", line 93, in _break_check",
    "    reachable = _check_if(context, check_node)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/flow_analysis.py\", line 120, in _check_if",
    "    types = context.infer_node(node)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/context.py\", line 222, in infer_node",
    "    return infer_node(self, node)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 156, in infer_node",
    "    return _infer_node_if_inferred(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 169, in _infer_node_if_inferred",
    "    return _infer_node_cached(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/cache.py\", line 44, in wrapper",
    "    rv = function(obj, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 174, in _infer_node_cached",
    "    return _infer_node(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/debug.py\", line 81, in wrapper",
    "    return func(*args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 82, in wrapper",
    "    return func(context, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 184, in _infer_node",
    "    return infer_atom(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 304, in infer_atom",
    "    return context.py__getattribute__(atom, position=position)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/context.py\", line 75, in py__getattribute__",
    "    values = ValueSet.from_sets(name.infer() for name in names)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 426, in from_sets",
    "    for set_ in sets:",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/context.py\", line 75, in <genexpr>",
    "    values = ValueSet.from_sets(name.infer() for name in names)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/names.py\", line 284, in infer",
    "    self.tree_name",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/plugins/__init__.py\", line 21, in wrapper",
    "    return built_functions[public_name](*args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/plugins/stdlib.py\", line 867, in wrapper",
    "    return func(inference_state, context, tree_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/plugins/django.py\", line 177, in wrapper",
    "    result = func(inference_state, context, tree_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 744, in tree_name_to_values",
    "    types = imports.infer_import(context, tree_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/cache.py\", line 44, in wrapper",
    "    rv = function(obj, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/imports.py\", line 60, in infer_import",
    "    analysis_errors=False",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 492, in py__getattribute__",
    "    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 426, in from_sets",
    "    for set_ in sets:",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 492, in <genexpr>",
    "    return ValueSet.from_sets(c.py__getattribute__(*args, **kwargs) for c in self._set)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 80, in py__getattribute__",
    "    values = ValueSet.from_sets(name.infer() for name in names)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 426, in from_sets",
    "    for set_ in sets:",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/base_value.py\", line 80, in <genexpr>",
    "    values = ValueSet.from_sets(name.infer() for name in names)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/names.py\", line 648, in infer",
    "    inferred = super().infer()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/names.py\", line 284, in infer",
    "    self.tree_name",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/plugins/__init__.py\", line 21, in wrapper",
    "    return built_functions[public_name](*args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/plugins/stdlib.py\", line 867, in wrapper",
    "    return func(inference_state, context, tree_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/plugins/django.py\", line 177, in wrapper",
    "    result = func(inference_state, context, tree_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 738, in tree_name_to_values",
    "    types = infer_expr_stmt(context, node, tree_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 82, in wrapper",
    "    return func(context, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 376, in infer_expr_stmt",
    "    return _infer_expr_stmt(context, stmt, seek_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/debug.py\", line 81, in wrapper",
    "    return func(*args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 409, in _infer_expr_stmt",
    "    value_set = context.infer_node(rhs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/context.py\", line 222, in infer_node",
    "    return infer_node(self, node)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 156, in infer_node",
    "    return _infer_node_if_inferred(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 169, in _infer_node_if_inferred",
    "    return _infer_node_cached(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/cache.py\", line 44, in wrapper",
    "    rv = function(obj, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 174, in _infer_node_cached",
    "    return _infer_node(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/debug.py\", line 81, in wrapper",
    "    return func(*args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 82, in wrapper",
    "    return func(context, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 184, in _infer_node",
    "    return infer_atom(context, element)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/syntax_tree.py\", line 308, in infer_atom",
    "    return ValueSet([compiled.builtin_from_name(state, atom.value)])",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/__init__.py\", line 17, in builtin_from_name",
    "    value, = name.infer()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/value.py\", line 354, in infer",
    "    return ValueSet([self.infer_compiled_value()])",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/cache.py\", line 112, in wrapper",
    "    result = method(self, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/value.py\", line 358, in infer_compiled_value",
    "    return create_from_name(self._inference_state, self._parent_value, self.string_name)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/value.py\", line 580, in create_from_name",
    "    access_paths = compiled_value.access_handle.getattr_paths(name, default=None)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/subprocess/__init__.py\", line 386, in _workaround",
    "    return self._cached_results(name, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/cache.py\", line 112, in wrapper",
    "    result = method(self, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/subprocess/__init__.py\", line 390, in _cached_results",
    "    return self._subprocess.get_compiled_method_return(self.id, name, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/subprocess/__init__.py\", line 133, in wrapper",
    "    kwargs=kwargs,",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/subprocess/__init__.py\", line 226, in run",
    "    return self._send(id(inference_state), function, args, kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/compiled/subprocess/__init__.py\", line 245, in _send",
    "    % self._executable)",
    "jedi.api.exceptions.InternalError: The subprocess /usr/share/miniconda/envs/test/bin/python was killed. Maybe out of memory?",
    ""
   ]
  },
  "snowflake.connector.constants": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/constants.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/constants.py'",
    ""
   ]
  },
  "snowflake.connector.dbapi": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/dbapi.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/dbapi.py'",
    ""
   ]
  },
  "snowflake.connector.encryption_util": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/encryption_util.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/encryption_util.py'",
    ""
   ]
  },
  "snowflake.connector.errors": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/errors.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/errors.py'",
    ""
   ]
  },
  "snowflake.connector.feature": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/feature.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/feature.py'",
    ""
   ]
  },
  "snowflake.connector.file_compression_type": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/file_compression_type.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/file_compression_type.py'",
    ""
   ]
  },
  "snowflake.connector.incident": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/incident.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/incident.py'",
    ""
   ]
  },
  "snowflake.connector.json_result": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/json_result.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/json_result.py'",
    ""
   ]
  },
  "snowflake.connector.network": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/network.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/network.py'",
    ""
   ]
  },
  "snowflake.connector.ocsp_pyasn1": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/ocsp_pyasn1.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/ocsp_pyasn1.py'",
    ""
   ]
  },
  "snowflake.connector.remote_storage_util": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/remote_storage_util.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/remote_storage_util.py'",
    ""
   ]
  },
  "snowflake.connector.rfc6960": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/rfc6960.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/rfc6960.py'",
    ""
   ]
  },
  "snowflake.connector.sfdatetime": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/sfdatetime.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/sfdatetime.py'",
    ""
   ]
  },
  "snowflake.connector.ssd_internal_keys": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/ssd_internal_keys.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/ssd_internal_keys.py'",
    ""
   ]
  },
  "snowflake.connector.ssl_wrap_util": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_util.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/ssl_wrap_util.py'",
    ""
   ]
  },
  "snowflake.connector.tool": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/__init__.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/__init__.py'",
    ""
   ]
  },
  "snowflake.connector.tool.dump_certs": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/dump_certs.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/dump_certs.py'",
    ""
   ]
  },
  "snowflake.connector.tool.dump_ocsp_response": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/dump_ocsp_response.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/dump_ocsp_response.py'",
    ""
   ]
  },
  "snowflake.connector.tool.dump_ocsp_response_cache": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/dump_ocsp_response_cache.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/dump_ocsp_response_cache.py'",
    ""
   ]
  },
  "snowflake.connector.tool.probe_connection": {
   "exception": "[Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/probe_connection.py'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 111, in __init__",
    "    with open(path, 'rb') as f:",
    "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmnrze6hc/lib/python3.7/site-packages/snowflake/connector/tool/probe_connection.py'",
    ""
   ]
  }
 },
 "symbols": [
  "snowflake.connector.auth.AuthByPlugin.assertion_content",
  "snowflake.connector.auth_keypair.AuthByKeyPair",
  "snowflake.connector.auth_keypair.assertion_content",
  "snowflake.connector.auth_keypair.logger",
  "snowflake.connector.auth_okta.AuthByOkta",
  "snowflake.connector.auth_okta._get_post_back_url_from_html",
  "snowflake.connector.auth_okta._is_prefix_equal",
  "snowflake.connector.auth_okta.assertion_content",
  "snowflake.connector.auth_okta.logger",
  "snowflake.connector.auth_webbrowser.AuthByWebBrowser",
  "snowflake.connector.auth_webbrowser.BUF_SIZE",
  "snowflake.connector.auth_webbrowser.assertion_content",
  "snowflake.connector.auth_webbrowser.logger",
  "snowflake.connector.backport_makefile.backport_makefile",
  "snowflake.connector.compat.OK",
  "snowflake.connector.compat.urlsplit",
  "snowflake.connector.connection.APPLICATION_RE",
  "snowflake.connector.connection.APPLICATION_SNOWSQL",
  "snowflake.connector.connection.DEFAULT_CONFIGURATION",
  "snowflake.connector.connection.DefaultConverterClass",
  "snowflake.connector.connection.SUPPORTED_PARAMSTYLES",
  "snowflake.connector.connection.SnowflakeConnection",
  "snowflake.connector.connection.logger",
  "snowflake.connector.connection.m",
  "snowflake.connector.constants.HTTP_HEADER_USER_AGENT",
  "snowflake.connector.converter.BITS_FOR_TIMEZONE",
  "snowflake.connector.converter.PYTHON_TO_SNOWFLAKE_TYPE",
  "snowflake.connector.converter.SnowflakeConverter",
  "snowflake.connector.converter.SnowflakeConverter._ARRAY_to_python",
  "snowflake.connector.converter.SnowflakeConverter._OBJECT_to_python",
  "snowflake.connector.converter.SnowflakeConverter._TIMESTAMP_to_python",
  "snowflake.connector.converter.SnowflakeConverter._bytearray_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._bytearray_to_snowflake_bindings",
  "snowflake.connector.converter.SnowflakeConverter._decimal_to_snowflake_bindings",
  "snowflake.connector.converter.SnowflakeConverter._float16_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._float32_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._float64_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._float_to_snowflake_bindings",
  "snowflake.connector.converter.SnowflakeConverter._int16_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._int32_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._int64_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._int8_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._int_to_snowflake_bindings",
  "snowflake.connector.converter.SnowflakeConverter._long_to_snowflake_bindings",
  "snowflake.connector.converter.SnowflakeConverter._tuple_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._uint16_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._uint32_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._uint64_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._uint8_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._unicode_to_snowflake",
  "snowflake.connector.converter.SnowflakeConverter._unicode_to_snowflake_bindings",
  "snowflake.connector.converter.ZERO_EPOCH",
  "snowflake.connector.converter.ZERO_EPOCH_DATE",
  "snowflake.connector.converter.ZERO_FILL",
  "snowflake.connector.converter.ZERO_TIMEDELTA",
  "snowflake.connector.converter._TZINFO_CLASS_CACHE",
  "snowflake.connector.converter._adjust_fraction_of_nanoseconds",
  "snowflake.connector.converter._convert_date_to_epoch_milliseconds",
  "snowflake.connector.converter._convert_datetime_to_epoch_nanoseconds",
  "snowflake.connector.converter._convert_time_to_epoch_nanoseconds",
  "snowflake.connector.converter._extract_timestamp",
  "snowflake.connector.converter._generate_tzinfo_from_tzoffset",
  "snowflake.connector.converter.convert_datetime_to_epoch",
  "snowflake.connector.converter.logger",
  "snowflake.connector.converter.numpy",
  "snowflake.connector.converter.tzlocal",
  "snowflake.connector.converter_issue23517.SnowflakeConverterIssue23517",
  "snowflake.connector.converter_issue23517._ARRAY_to_python",
  "snowflake.connector.converter_issue23517._OBJECT_to_python",
  "snowflake.connector.converter_issue23517._TIMESTAMP_to_python",
  "snowflake.connector.converter_issue23517._bytearray_to_snowflake",
  "snowflake.connector.converter_issue23517._bytearray_to_snowflake_bindings",
  "snowflake.connector.converter_issue23517._decimal_to_snowflake_bindings",
  "snowflake.connector.converter_issue23517._float16_to_snowflake",
  "snowflake.connector.converter_issue23517._float32_to_snowflake",
  "snowflake.connector.converter_issue23517._float64_to_snowflake",
  "snowflake.connector.converter_issue23517._float_to_snowflake_bindings",
  "snowflake.connector.converter_issue23517._int16_to_snowflake",
  "snowflake.connector.converter_issue23517._int32_to_snowflake",
  "snowflake.connector.converter_issue23517._int64_to_snowflake",
  "snowflake.connector.converter_issue23517._int8_to_snowflake",
  "snowflake.connector.converter_issue23517._int_to_snowflake_bindings",
  "snowflake.connector.converter_issue23517._long_to_snowflake_bindings",
  "snowflake.connector.converter_issue23517._tuple_to_snowflake",
  "snowflake.connector.converter_issue23517._uint16_to_snowflake",
  "snowflake.connector.converter_issue23517._uint32_to_snowflake",
  "snowflake.connector.converter_issue23517._uint64_to_snowflake",
  "snowflake.connector.converter_issue23517._uint8_to_snowflake",
  "snowflake.connector.converter_issue23517._unicode_to_snowflake",
  "snowflake.connector.converter_issue23517._unicode_to_snowflake_bindings",
  "snowflake.connector.converter_issue23517.logger",
  "snowflake.connector.converter_null.SnowflakeNoConverterToPython",
  "snowflake.connector.converter_null._ARRAY_to_python",
  "snowflake.connector.converter_null._OBJECT_to_python",
  "snowflake.connector.converter_null._TIMESTAMP_to_python",
  "snowflake.connector.converter_null._bytearray_to_snowflake",
  "snowflake.connector.converter_null._bytearray_to_snowflake_bindings",
  "snowflake.connector.converter_null._decimal_to_snowflake_bindings",
  "snowflake.connector.converter_null._float16_to_snowflake",
  "snowflake.connector.converter_null._float32_to_snowflake",
  "snowflake.connector.converter_null._float64_to_snowflake",
  "snowflake.connector.converter_null._float_to_snowflake_bindings",
  "snowflake.connector.converter_null._int16_to_snowflake",
  "snowflake.connector.converter_null._int32_to_snowflake",
  "snowflake.connector.converter_null._int64_to_snowflake",
  "snowflake.connector.converter_null._int8_to_snowflake",
  "snowflake.connector.converter_null._int_to_snowflake_bindings",
  "snowflake.connector.converter_null._long_to_snowflake_bindings",
  "snowflake.connector.converter_null._tuple_to_snowflake",
  "snowflake.connector.converter_null._uint16_to_snowflake",
  "snowflake.connector.converter_null._uint32_to_snowflake",
  "snowflake.connector.converter_null._uint64_to_snowflake",
  "snowflake.connector.converter_null._uint8_to_snowflake",
  "snowflake.connector.converter_null._unicode_to_snowflake",
  "snowflake.connector.converter_null._unicode_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql.SnowflakeConverterSnowSQL",
  "snowflake.connector.converter_snowsql._ARRAY_to_python",
  "snowflake.connector.converter_snowsql._OBJECT_to_python",
  "snowflake.connector.converter_snowsql._TIMESTAMP_to_python",
  "snowflake.connector.converter_snowsql._bytearray_to_snowflake",
  "snowflake.connector.converter_snowsql._bytearray_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql._decimal_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql._float16_to_snowflake",
  "snowflake.connector.converter_snowsql._float32_to_snowflake",
  "snowflake.connector.converter_snowsql._float64_to_snowflake",
  "snowflake.connector.converter_snowsql._float_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql._int16_to_snowflake",
  "snowflake.connector.converter_snowsql._int32_to_snowflake",
  "snowflake.connector.converter_snowsql._int64_to_snowflake",
  "snowflake.connector.converter_snowsql._int8_to_snowflake",
  "snowflake.connector.converter_snowsql._int_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql._long_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql._tuple_to_snowflake",
  "snowflake.connector.converter_snowsql._uint16_to_snowflake",
  "snowflake.connector.converter_snowsql._uint32_to_snowflake",
  "snowflake.connector.converter_snowsql._uint64_to_snowflake",
  "snowflake.connector.converter_snowsql._uint8_to_snowflake",
  "snowflake.connector.converter_snowsql._unicode_to_snowflake",
  "snowflake.connector.converter_snowsql._unicode_to_snowflake_bindings",
  "snowflake.connector.converter_snowsql.format_sftimestamp",
  "snowflake.connector.converter_snowsql.logger",
  "snowflake.connector.cursor.DESC_TABLE_RE",
  "snowflake.connector.cursor.DictCursor",
  "snowflake.connector.cursor.LOG_MAX_QUERY_LENGTH",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_DELETE",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_DML",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_DML_SET",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_INSERT",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_MERGE",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_MULTI_TABLE_INSERT",
  "snowflake.connector.cursor.STATEMENT_TYPE_ID_UPDATE",
  "snowflake.connector.cursor.SnowflakeCursor",
  "snowflake.connector.cursor.logger",
  "snowflake.connector.errorcode.ER_CA_CERTIFICATE_NOT_FOUND",
  "snowflake.connector.errorcode.ER_CHUNK_DOWNLOAD_FAILED",
  "snowflake.connector.errorcode.ER_COMPRESSION_NOT_SUPPORTED",
  "snowflake.connector.errorcode.ER_CONNECTION_IS_CLOSED",
  "snowflake.connector.errorcode.ER_CURSOR_IS_CLOSED",
  "snowflake.connector.errorcode.ER_FAILED_PROCESSING_PYFORMAT",
  "snowflake.connector.errorcode.ER_FAILED_TO_CHECK_EXISTING_FILES",
  "snowflake.connector.errorcode.ER_FAILED_TO_CONNECT_TO_DB",
  "snowflake.connector.errorcode.ER_FAILED_TO_CONVERT_ROW_TO_PYTHON_TYPE",
  "snowflake.connector.errorcode.ER_FAILED_TO_DOWNLOAD_FROM_STAGE",
  "snowflake.connector.errorcode.ER_FAILED_TO_GET_BOOTSTRAP",
  "snowflake.connector.errorcode.ER_FAILED_TO_GET_CERTIFICATE_CHAIN",
  "snowflake.connector.errorcode.ER_FAILED_TO_GET_OCSP_URI",
  "snowflake.connector.errorcode.ER_FAILED_TO_GET_X509",
  "snowflake.connector.errorcode.ER_FAILED_TO_RENEW_SESSION",
  "snowflake.connector.errorcode.ER_FAILED_TO_REQUEST",
  "snowflake.connector.errorcode.ER_FAILED_TO_REWRITE_MULTI_ROW_INSERT",
  "snowflake.connector.errorcode.ER_FAILED_TO_SERVER",
  "snowflake.connector.errorcode.ER_FAILED_TO_UPLOAD_TO_STAGE",
  "snowflake.connector.errorcode.ER_FILE_NOT_EXISTS",
  "snowflake.connector.errorcode.ER_IDP_CONNECTION_ERROR",
  "snowflake.connector.errorcode.ER_INCORRECT_DESTINATION",
  "snowflake.connector.errorcode.ER_INTERNAL_NOT_MATCH_ENCRYPT_MATERIAL",
  "snowflake.connector.errorcode.ER_INVALID_CERTIFICATE",
  "snowflake.connector.errorcode.ER_INVALID_OCSP_RESPONSE",
  "snowflake.connector.errorcode.ER_INVALID_OCSP_RESPONSE_CODE",
  "snowflake.connector.errorcode.ER_INVALID_PRIVATE_KEY",
  "snowflake.connector.errorcode.ER_INVALID_SSD",
  "snowflake.connector.errorcode.ER_INVALID_STAGE_FS",
  "snowflake.connector.errorcode.ER_INVALID_STAGE_LOCATION",
  "snowflake.connector.errorcode.ER_INVALID_VALUE",
  "snowflake.connector.errorcode.ER_LOCAL_PATH_NOT_DIRECTORY",
  "snowflake.connector.errorcode.ER_NOT_HTTPS_USED",
  "snowflake.connector.errorcode.ER_NOT_IMPLICITY_SNOWFLAKE_DATATYPE",
  "snowflake.connector.errorcode.ER_NOT_POSITIVE_SIZE",
  "snowflake.connector.errorcode.ER_NOT_SUPPORT_DATA_TYPE",
  "snowflake.connector.errorcode.ER_NO_ACCOUNT_NAME",
  "snowflake.connector.errorcode.ER_NO_ADDITIONAL_CHUNK",
  "snowflake.connector.errorcode.ER_NO_CURL_CONFIG_FOUND",
  "snowflake.connector.errorcode.ER_NO_DATA_FOUND",
  "snowflake.connector.errorcode.ER_NO_HOSTNAME_FOUND",
  "snowflake.connector.errorcode.ER_NO_PASSWORD",
  "snowflake.connector.errorcode.ER_NO_USER",
  "snowflake.connector.errorcode.ER_NO_WINDOWS_SUPPORT",
  "snowflake.connector.errorcode.ER_OCSP_FAILED_TO_CONNECT_HOST",
  "snowflake.connector.errorcode.ER_OLD_PYTHON",
  "snowflake.connector.errorcode.ER_OPENSSL_IS_NOT_ACCESSIBLE",
  "snowflake.connector.errorcode.ER_SERVER_CERTIFICATE_REVOKED",
  "snowflake.connector.errorcode.ER_SERVER_CERTIFICATE_UNKNOWN",
  "snowflake.connector.errorcode.ER_UNABLE_TO_OPEN_BROWSER",
  "snowflake.connector.errorcode.ER_UNABLE_TO_START_WEBSERVER",
  "snowflake.connector.errorcode.ER_UNSUPPORTED_METHOD",
  "snowflake.connector.errors.RevocationCheckError",
  "snowflake.connector.file_transfer_agent.AZURE_FS",
  "snowflake.connector.file_transfer_agent.CMD_TYPE_DOWNLOAD",
  "snowflake.connector.file_transfer_agent.CMD_TYPE_UPLOAD",
  "snowflake.connector.file_transfer_agent.INJECT_WAIT_IN_PUT",
  "snowflake.connector.file_transfer_agent.LOCAL_FS",
  "snowflake.connector.file_transfer_agent.MB",
  "snowflake.connector.file_transfer_agent.RESULT_FIXED_COLUMN_DESC",
  "snowflake.connector.file_transfer_agent.RESULT_TEXT_COLUMN_DESC",
  "snowflake.connector.file_transfer_agent.S3_FS",
  "snowflake.connector.file_transfer_agent.SnowflakeAzureProgressPercentage",
  "snowflake.connector.file_transfer_agent.SnowflakeFileTransferAgent",
  "snowflake.connector.file_transfer_agent.SnowflakeProgressPercentage",
  "snowflake.connector.file_transfer_agent.SnowflakeS3ProgressPercentage",
  "snowflake.connector.file_transfer_agent._update_progress",
  "snowflake.connector.file_transfer_agent.logger",
  "snowflake.connector.file_util.SnowflakeFileUtil",
  "snowflake.connector.gzip_decoder.CHUNK_SIZE",
  "snowflake.connector.gzip_decoder.IterStreamer",
  "snowflake.connector.gzip_decoder.MAGIC_NUMBER",
  "snowflake.connector.gzip_decoder.decompress_raw_data",
  "snowflake.connector.gzip_decoder.logger",
  "snowflake.connector.local_util.SnowflakeLocalUtil",
  "snowflake.connector.mixin.UnicodeMixin",
  "snowflake.connector.network.APPLICATION_SNOWSQL",
  "snowflake.connector.network.PYTHON_CONNECTOR_USER_AGENT",
  "snowflake.connector.ocsp_asn1crypto.ER_INVALID_OCSP_RESPONSE",
  "snowflake.connector.ocsp_asn1crypto.ER_INVALID_OCSP_RESPONSE_CODE",
  "snowflake.connector.ocsp_asn1crypto.RevocationCheckError",
  "snowflake.connector.ocsp_asn1crypto.SnowflakeOCSP",
  "snowflake.connector.ocsp_asn1crypto.SnowflakeOCSPAsn1Crypto",
  "snowflake.connector.ocsp_asn1crypto.logger",
  "snowflake.connector.ocsp_asn1crypto.ret_wildcard_hkey",
  "snowflake.connector.ocsp_snowflake.DecorrelateJitterBackoff",
  "snowflake.connector.ocsp_snowflake.ER_INVALID_OCSP_RESPONSE",
  "snowflake.connector.ocsp_snowflake.ER_INVALID_OCSP_RESPONSE_CODE",
  "snowflake.connector.ocsp_snowflake.ER_INVALID_SSD",
  "snowflake.connector.ocsp_snowflake.ER_OCSP_FAILED_TO_CONNECT_HOST",
  "snowflake.connector.ocsp_snowflake.ER_SERVER_CERTIFICATE_REVOKED",
  "snowflake.connector.ocsp_snowflake.ER_SERVER_CERTIFICATE_UNKNOWN",
  "snowflake.connector.ocsp_snowflake.HTTP_HEADER_USER_AGENT",
  "snowflake.connector.ocsp_snowflake.OCSPCache",
  "snowflake.connector.ocsp_snowflake.OCSPServer",
  "snowflake.connector.ocsp_snowflake.OCSPTelemetryData",
  "snowflake.connector.ocsp_snowflake.OK",
  "snowflake.connector.ocsp_snowflake.PYTHON_CONNECTOR_USER_AGENT",
  "snowflake.connector.ocsp_snowflake.RevocationCheckError",
  "snowflake.connector.ocsp_snowflake.SFSsd",
  "snowflake.connector.ocsp_snowflake.SSDPubKey",
  "snowflake.connector.ocsp_snowflake.SnowflakeOCSP",
  "snowflake.connector.ocsp_snowflake.logger",
  "snowflake.connector.ocsp_snowflake.ocsp_internal_dep1_key_ver",
  "snowflake.connector.ocsp_snowflake.ocsp_internal_dep2_key_ver",
  "snowflake.connector.ocsp_snowflake.ocsp_internal_ssd_pub_dep1",
  "snowflake.connector.ocsp_snowflake.ocsp_internal_ssd_pub_dep2",
  "snowflake.connector.ocsp_snowflake.urlsplit",
  "snowflake.connector.proxy.set_proxies",
  "snowflake.connector.s3_util.ADDRESSING_STYLE",
  "snowflake.connector.s3_util.AMZ_IV",
  "snowflake.connector.s3_util.AMZ_KEY",
  "snowflake.connector.s3_util.AMZ_MATDESC",
  "snowflake.connector.s3_util.ERRORNO_WSAECONNABORTED",
  "snowflake.connector.s3_util.EXPIRED_TOKEN",
  "snowflake.connector.s3_util.S3Location",
  "snowflake.connector.s3_util.SFC_DIGEST",
  "snowflake.connector.s3_util.SnowflakeS3Util",
  "snowflake.connector.sfbinaryformat.SnowflakeBinaryFormat",
  "snowflake.connector.sfbinaryformat.binary_to_python",
  "snowflake.connector.sfbinaryformat.binary_to_snowflake",
  "snowflake.connector.sqlstate.SQLSTATE_CONNECTION_ALREADY_EXISTS",
  "snowflake.connector.sqlstate.SQLSTATE_CONNECTION_FAILED_BUT_REESTABLISHED",
  "snowflake.connector.sqlstate.SQLSTATE_CONNECTION_NOT_EXISTS",
  "snowflake.connector.sqlstate.SQLSTATE_CONNECTION_REJECTED",
  "snowflake.connector.sqlstate.SQLSTATE_CONNECTION_WAS_NOT_ESTABLISHED",
  "snowflake.connector.sqlstate.SQLSTATE_FEATURE_NOT_SUPPORTED",
  "snowflake.connector.sqlstate.SQLSTATE_HOST_NOT_FOUND",
  "snowflake.connector.ssd_internal_keys.ocsp_internal_dep1_key_ver",
  "snowflake.connector.ssd_internal_keys.ocsp_internal_dep2_key_ver",
  "snowflake.connector.ssd_internal_keys.ocsp_internal_ssd_pub_dep1",
  "snowflake.connector.ssd_internal_keys.ocsp_internal_ssd_pub_dep2",
  "snowflake.connector.ssd_internal_keys.ret_wildcard_hkey",
  "snowflake.connector.ssl_wrap_socket.DEFAULT_SSL_CIPHER_LIST",
  "snowflake.connector.ssl_wrap_socket.FEATURE_OCSP_MODE",
  "snowflake.connector.ssl_wrap_socket.FEATURE_OCSP_RESPONSE_CACHE_FILE_NAME",
  "snowflake.connector.ssl_wrap_socket.SSL_WRITE_BLOCKSIZE",
  "snowflake.connector.ssl_wrap_socket.WrappedSocket",
  "snowflake.connector.ssl_wrap_socket._dnsname_to_stdlib",
  "snowflake.connector.ssl_wrap_socket._fileobject",
  "snowflake.connector.ssl_wrap_socket._openssl_connect",
  "snowflake.connector.ssl_wrap_socket._openssl_to_stdlib_verify",
  "snowflake.connector.ssl_wrap_socket._openssl_versions",
  "snowflake.connector.ssl_wrap_socket._stdlib_to_openssl_verify",
  "snowflake.connector.ssl_wrap_socket._verify_callback",
  "snowflake.connector.ssl_wrap_socket.get_subj_alt_name",
  "snowflake.connector.ssl_wrap_socket.inject_into_urllib3",
  "snowflake.connector.ssl_wrap_socket.log",
  "snowflake.connector.ssl_wrap_socket.makefile",
  "snowflake.connector.ssl_wrap_socket.ssl_wrap_socket",
  "snowflake.connector.telemetry.TelemetryClient",
  "snowflake.connector.telemetry.TelemetryData",
  "snowflake.connector.telemetry.TelemetryField",
  "snowflake.connector.telemetry.logger",
  "snowflake.connector.time_util.DEFAULT_MASTER_VALIDITY_IN_SECONDS",
  "snowflake.connector.time_util.DecorrelateJitterBackoff",
  "snowflake.connector.time_util.HeartBeatTimer",
  "snowflake.connector.time_util.get_time_millis",
  "snowflake.connector.time_util.logger",
  "snowflake.connector.util_text.COMMENT_PATTERN_RE",
  "snowflake.connector.util_text.EMPTY_LINE_RE",
  "snowflake.connector.util_text._concatenate_statements",
  "snowflake.connector.util_text._logger",
  "snowflake.connector.util_text.construct_hostname",
  "snowflake.connector.util_text.parse_account",
  "snowflake.connector.util_text.split_rows_from_stream",
  "snowflake.connector.util_text.split_statements",
  "snowflake.connector.version.VERSION"
 ]
}